### ISSUE TITLE
How do I uninstall this or disable it from automatically running?

### ISSUE THREAD

**Issue by isayakmondal** [sanketkheni01/Desktop-Switch-Animation-Win11#2]
So I've tried checking under the Startup section in Task Manager but it doesn't show up. Please provide a way to do so.

**Comment by TheFatherMind** [comment]
IDK why I am seeing this as I am not using the app.  However, Windows has many startup locations.
Get this app (you can get a portable version if you like): https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns
Look on the "Logon" tab as well as the "Scheduled Tasks" tab.  You will likely find it.  You can delete the entry or disable it from there.

**Comment by sanketkheni01** [comment]
@isayakmondal Readme updated. thanks for the suggestion.

**Comment by isayakmondal** [comment]
@sanketkheni01 Thanks! However the issue #1  is same for me as well, so I'm using the 1.2 version. If possible kindly take a look.
